name: Linters

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: ["3.11", "3.12", "3.13"]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip wheel
                  pip install -r requirements-test.txt -e .
            - name: Run Tests
              run: |
                  pytest --cov=aptly_api
                  coverage report -m
                  coverage lcov
            - name: Run Coveralls
              uses: coverallsapp/github-action@main
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: coverage.lcov
            - name: Run Flake8
              run: |
                  flake8 --max-line-length=120 aptly_api setup.py
            - name: Run mypy
              run: |
                  mypy --install-types --non-interactive \
                       --ignore-missing-imports --follow-imports=skip --disallow-untyped-calls \
                       --disallow-untyped-defs -p aptly_api
